#!/usr/bin/env python3
"""Generates a KubeJS script that dumps concrete item ids for every tag
referenced by a parsed recipes.jsonl (rather than every tag in the game).

Usage:
    python3 generate_tag_dump_script.py recipes.jsonl dump_tags.js

Copy the resulting dump_tags.js to your server_scripts folder and run it
the same way as dump_recipes.js, then:
    grep "TAGDUMP " logs/latest.log > tags_raw.txt
"""

import json
import sys


def collect_tags(recipes_jsonl_path):
    tags = set()

    def walk(x):
        if isinstance(x, dict):
            if isinstance(x.get("tag"), str):
                tags.add(x["tag"])
            for v in x.values():
                walk(v)
        elif isinstance(x, list):
            for v in x:
                walk(v)

    with open(recipes_jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            walk(r["json"])
    return sorted(tags)


TEMPLATE = """\
// Dumps the concrete item ids for every tag actually referenced by
// recipes.jsonl (generated by db/generate_tag_dump_script.py), using
// KubeJS's own tag wrapper - no raw Java access needed.
//
// NOTE: ServerEvents.tags fires multiple times during server startup/reload;
// early firings (before tags fully resolve) return empty/garbage results, and
// a later "Worker-ResourceReload" thread firing has the real resolved data.
// db/parse_tag_log.py handles this (keeps the LAST occurrence per tag) - it's
// expected and not a bug if you see a tag logged more than once.
ServerEvents.tags('item', event => {{
  let tagIds = {tag_array}

  let count = 0
  tagIds.forEach(tagId => {{
    try {{
      let ids = event.get(tagId).getObjectIds()
      // ids is a Java List, not a JS array - .map()/.forEach() don't work on
      // it the way they would on a real array, so build one by hand.
      let arr = []
      for (let i = 0; i < ids.size(); i++) {{
        arr.push(String(ids.get(i)))
      }}
      console.log('TAGDUMP ' + tagId + ' ' + JSON.stringify(arr))
      count++
    }} catch (e) {{
      console.log('TAGDUMP ' + tagId + ' <error: ' + e + '>')
    }}
  }})
  console.log('TAGDUMP_TOTAL ' + count)
}})
"""


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    recipes_path, out_path = sys.argv[1], sys.argv[2]

    tags = collect_tags(recipes_path)
    script = TEMPLATE.format(tag_array=json.dumps(tags, indent=2))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"distinct tags referenced: {len(tags)}")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
